import os

CELL_SIZE = 30
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 850

GRID_ROWS = SCREEN_HEIGHT // CELL_SIZE
GRID_COLUMNS = SCREEN_WIDTH // CELL_SIZE

MAZE_GRID_ROWS = GRID_ROWS - 2
MAZE_GRID_COLUMNS = GRID_COLUMNS

UI_HEIGHT = CELL_SIZE * 2
MAZE_OFFSET_X = CELL_SIZE // 2
MAZE_OFFSET_Y = UI_HEIGHT + CELL_SIZE // 2

PLAYER_MOVE_SPEED = 3
ENEMY_NUMBER = 4
ENEMY_MOVE_SPEED = 2
ENEMY_RADAR = CELL_SIZE * 5

DEBUG_MODE = os.getenv('DEBUG_MODE') == '1'
